version: '3.9'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:${DB_PASSWORD}@postgres:5432/fastapi_db
    depends_on:
      - postgres
    networks:
      - fastapi_network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=fastapi_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "fastapi_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks:
      - fastapi_network

networks:
  fastapi_network:
