version: "3.8"
services:
  fastapi:
    build:
      context: ./fastapi_project
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: fastapi_db
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: fastapi_db
    networks:
      - app_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
