services:
  db:
    image: postgres:latest
    container_name: postgresql_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_container
    environment:
      DATABASE_URL: postgresql://postgres:pass@postgresql_container:5432/fastapi_db
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  db_data:
